# Generated by Django 4.2.6 on 2023-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_match', '0003_alter_movie_original_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
