# Generated by Django 4.2.6 on 2023-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_match', '0004_alter_movie_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
